<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<LangVersion>10.0</LangVersion>
	<Configurations>Debug;Release;Alpha;Beta</Configurations>
	<PlatformTarget>AnyCPU</PlatformTarget>
	<SignAssembly>False</SignAssembly>
	<ApplicationIcon>Image\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Alpha' ">
	<OutputPath>bin\Alpha\</OutputPath>
	<DefineConstants>ALPHA</DefineConstants>
	<Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Beta' ">
	<OutputPath>bin\Beta\</OutputPath>
	<DefineConstants>BETA</DefineConstants>
	<Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Image\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\XeF4Core\XeF4Core\XeF4Core.csproj" />
    <ProjectReference Include="..\XeF4Core.WPF\XeF4Core.WPF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
  </ItemGroup>

</Project>
